version: '3'
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
      - RABBITMQ_LOG_LEVELS='[{connection, error}]'
  ingress:
    hostname: ingress
    build: ingress/
    ports:
      - "8080:80"
    depends_on:
      - web-srv
      - ws-srv
    environment:
      - USE_LISTEN_PORT=80
      - HANDLER_ADDRESS=http://web-srv:5000/
      - WS_ADDRESS=http://ws-srv:5001/
  web-srv:
    hostname: web-srv
    build: web-srv/
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
    environment:
        - PORT=5000
        - FLASK_DEBUG=1
        - AMQP_URL=amqp://admin:mypass@rabbit:5672/%2f
  ws-srv:
    hostname: ws-srv
    build: ws-srv/
    ports:
      - "5001:5001"
    depends_on:
      - rabbit
    environment:
        - PORT=5001
  fib-svc:
    build: fib-svc/
    depends_on:
      - rabbit
    environment:
        - PORT=5001
        - AMQP_URL=amqp://admin:mypass@rabbit:5672/%2f
