version: '3'
services:
  ingress:
    hostname: ingress
    build: ingress/
    ports:
      - "8080:80"
    links:
      - web-srv
      - ws-srv
    depends_on:
      - web-srv
      - ws-srv
    environment:
      USE_LISTEN_PORT: 80
      HANDLER_ADDRESS: http://web-srv:5000/
      WS_ADDRESS: http://ws-srv:5001/
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
  web-srv:
    hostname: web-srv
    build: web-srv/
    ports:
      - "5000:5000"
    links:
      - rabbit
    depends_on:
      - rabbit
    environment:
        PORT: 5000
        FLASK_DEBUG: 1
  ws-srv:
    hostname: ws-srv
    build: ws-srv/
    ports:
      - "5001:5001"
    links:
      - rabbit
    depends_on:
      - rabbit
    environment:
        PORT: 5001
   
  # fib-svc:
  #   build: fib-svc/
  #   links:
  #     - rabbit
  #   depends_on:
  #     - rabbit
